; Copyright 1995-2015 by Freedom Scientific, Inc.
; JAWS 8.0
; Script message file for Borland Developer Studio

Const



;UNUSED_VARIABLES

; The scroll up and scroll down graphic labels
	scScrollUp = "scroll up symbol",
	scScrollDown = "scroll down symbol"

;END_OF_UNUSED_VARIABLES

messages
@msgBdsAppName
Borland Developer Studio
@@
@msgNoListAvailable_L
list not available
@@
@msgNoListAvailable_S
no list
@@
@msgHasSubItems
has sub items
@@
EndMessages
