; Copyright 1995-2021 by Freedom Scientific, Inc.
; This file contains aliases for configuration sets.  If the executable name
; is not a desirable configuration name, then put an alias in this file.  When
; the application focus changes, JAWS will read the executable name and check
; it against this file.  If a match is found, then the match will be used.
; Otherwise, JAWS will just use the executable filename.

[ConfigNames]
; exeName:version=configurationName
; - exeName is the file's name without the extension.
; - version is the file's major and minor version or just the major version,
;     without preceding zeros.  The version is optional and can be left out if
;     the alias is not version-specific.
; - configurationName is the name of the configuration set which will be loaded.

_ins0432=QuickTime Installation
_INS576=InstallShield Installation
acrobat=Adobe Acrobat
AcroRd32=Adobe Acrobat
BrowseUI=Internet Explorer
msntab=Internet Explorer
shdoclc=Internet Explorer
MSHTA=Internet Explorer
;IE7
ieframe=Internet Explorer
iexplore=Internet Explorer
dui70=Direct UI
FrameView=Frame Viewer
fsComRes=JAWS Window
GetVoices=JAWS Window
RemoteSupportUI=JAWS Window
jfw=JAWS Window
hhctrl=HTML and Windows Help
JDiction=Dictionary Manager
JKey=Keyboard Manager
JScript=Script Manager
jtl=JAWS Task List
AudibleDownloadHelper=AudibleManager
manager=AudibleManager
marscore=Internet Explorer
mso=Office
msohelp=Office Help
clview=Office Help 2007
mviewer2=Bible
nlNotes=Lotus Notes
nnotesws=Lotus Notes
notes2=Lotus Notes
notes2w=Lotus Notes
WinCal=Windows Calendar
winword=Word
wwlib=Word
; For apps running in WDAG, JAWS will see app names with -remote appended to them. 
winword-remote=WordWDAG

msaccess=Access
ppcore=Powerpoint
; For apps running in WDAG, JAWS will see app names with -remote appended to them. 
powerpnt-remote=PowerPointWDAG

nsterm=NS Elite
obu=OpenBook
mapir=Outlook
OutLlibr=Outlook
outlook=Outlook
olk=Outlook Modern
Microsoft.OutlookForWindows!Microsoft.OutlookforWindows=Outlook Modern
prwin13=Corel Presentations X3
prwin14=Corel Presentations X4
prwin15=Corel Presentations X5
prwin16=Corel Presentations X6
prwin17=Corel Presentations X7
prwin18=Corel Presentations X8
prwin19=Corel Presentations X9
prwin20=Corel Presentations 2020
qpw:13=Quattro Pro X3
qpw:14=Quattro Pro X4
qpw15=Quattro Pro X5
qpw16=Quattro Pro X6
qpw17=Quattro Pro X7
qpw18=Quattro Pro X8
qpw19=Quattro Pro X9
qpw20=Quattro Pro 2020
qw=Quicken
QWMAIN=Quicken
realplay=Real Player
setg3270=Real Player
r1puninst=Real Player
rundll32=System Dialogs
shell32=Windows OS
SHLWAPI=Windows OS
shcore=Windows OS
SNDRec32=Sound Recorder
sndvol=System Dialogs
sysomgr=Windows Components Dialog
vb6=Visual Basic 6
vbe=Visual Basic
vbe6=Visual Basic 6
WinZip32=WinZip
wpwin13=WordPerfect X3
wpwin14=WordPerfect X4
wpwin15=WordPerfect X5
wpwin16=WordPerfect X6
wpwin17=WordPerfect X7
wpwin18=WordPerfect X8
wpwin19=WordPerfect X9
wpwin20=WordPerfect 2020
wpwin21=WordPerfect 2021
;Compatibility with JAWS and MAGic:
Excel=Excel
crt=ssh
mstsc=Terminal Services
rdclientax=Terminal Services
msrdc=Terminal Services
CDViewer=Citrix
wfica32=Citrix
Citrix.DesktopViewer.App=Citrix
pchshell=Internet Explorer
wmp:9=Windows Media Player
wmp:10=Windows Media Player
wmp:11=Windows Media Player 11
wmp:12=Windows Media Player 11
LibreOffice=Symphony
LibreOfficeDev=Symphony
Hannover:3=Symphony
Symphony:1=Symphony
firefox:3=Firefox
theophil=Theophilos
OptionalFeatures=AppWiz
WebConferencePlugin=Web Conference Plug In
stikynot=Sticky Note
vmware-view=VMWare Remote
horizon-client=VMWare Remote
crtbora=VMWare PublishedApp
; Visual Studio:
; VS2010
devenv:10=Visual Studio 2010
; VS2012
devenv:11=Visual Studio 2010
; VS2013
devenv:12=Visual Studio 2010
; VS2015
devenv:14=Visual Studio 2010
; VS2017 and later
devenv=VisualStudio
; Legacy free VS versions
;Visual Studio Express for Web Development
wdexpress=Visual Studio 2010
;Visual Studio Express for Windows
VSWinExpress=Visual Studio 2010
;Visual Studio Express for Windows Desktop
VWDExpress=Visual Studio 2010

TWinUI=Windows UI
Win8PC Settings=PC Settings
;For Windows 10:
windows.immersivecontrolpanel=PC Settings
;Store and News for Windows 8:
;For Windows 10
Microsoft.LockApp=Win8LockAppHostFrameHostWindow
microsoft.WindowsCommunicationsApps=Microsoft Mail
Microsoft.BingWeather!App=Microsoft Weather
Microsoft.XboxGamingOverlay!App=GameBar


;The WiX installer uses XML, which doesn't allow ampersand in the file names, so the following configuration is renamed:
Win8Alarms & Clock=Win8Alarms and Clock
Microsoft.WindowsAlarms=Win8Alarms and Clock
;Windows 10 Lock screen:
LockApp=Win8LockAppHostFrameHostWindow
LockAppHost=Win8LockAppHostFrameHostWindow

;For Windows 10:
Microsoft.Windows.Cortana=Windows SearchUI
Microsoft.Windows.search=Windows SearchUI
Microsoft.Windows.StartMenuExperienceHost!App=Windows SearchUI
; For start screen in Windows 11
MicrosoftWindows.client.cbs=Windows SearchUI
MicrosoftWindows.Client.39072097=Windows SearchUI
Microsoft.Windows.ShellExperienceHost=ShellExperienceHost
Microsoft.WindowsCalculator=Windows Calculator
Microsoft.Windows.PeopleExperienceHost=PeopleExperienceHost
Microsoft.Office.OneNote!microsoft.onenoteim=Microsoft.Office.OneNote
ONENOTE=OneNote
;For Notepad in Windows 11:
Microsoft.WindowsNotepad!App=notepad


;Task Manager, for Windows 8 and 8.1 only:
taskmgr:6.3=Win8Task Manager

AiSquared.ZoomText.UI=ZoomText
aisquared.zoomtext.welcome=ZoomText
DocReader=ZoomText Reader
QuickAccessBar=ZoomText
Skype=Skype
Microsoft.SkypeApp!App=Skype
teams=Teams
msteams=Teams
ms-teams=Teams
Microsoft.GetHelp!App=GetHelp
Microsoft.GetHelp=GetHelp

Microsoft.Office.Desktop!Access=access
Microsoft.Office.Desktop!Lync=Lync

Microsoft.WindowsFeedbackHub=WindowsFeedbackHub

; For Bloomberg, specifically Bloomberg Terminal and Bloomberg Chat
BLPGRID=Chrome
Bplus.wtk2=Chrome
WINTRV=Chrome
wui2manager=Chrome
;Visual Studio Code
code=VisualStudioCode
code - insiders=VisualStudioCode
;edge
MicrosoftEdgeCP=MicrosoftEdge
MicrosoftPdfReader=MicrosoftEdge
; new edge uses Chromium:
msedge=msedge
Edg=msedge
zChatUI=ZoomSoftware
zVideoUI=ZoomSoftware
csrss=ZoomSoftware
Microsoft.WindowsTerminal!App=WindowsTerminal
Microsoft.WindowsTerminalPreview!App=WindowsTerminal
Microsoft.WindowsTerminalCanary!App=WindowsTerminal
SpotifyAB.SpotifyMusic!Spotify=Spotify
; UWP version of iTunes. The executable name is still iTunes.exe, but JAWS relies on the package name  as the app name for UWP apps
AppleInc.iTunes!iTunes=iTunes
ETSChrome=Chrome
Microsoft.WindowsStore!App=MicrosoftStore
Microsoft.YourPhone!App=PhoneLink
Microsoft.ZuneMusic=MediaPlayer
; The below is not an error: Secure Assessment Browser uses legacy Edge
Microsoft.Windows.SecureAssessmentBrowser=MicrosoftEdge
rstrui=System Dialogs
5319275A.WhatsAppDesktop=WhatsApp
5319275A.51895FA4EA97F!App=WhatsApp
GateManagerServer=EAP
MessageCenterUI=MessageCenter
; Electron-based Thorium Ebook reader
thorium=chrome
; The following are defined for Cerner corporation
hla history=Cerner
define organ donor=Cerner
define organ recipient=Cerner
hla haplotype chart=Cerner
patprdinqry=Cerner
producthistoryreview=Cerner
reportselection=Cerner
collectionsresolution=Cerner
osmrequisitionorderentry=Cerner
csmcallin=Cerner
pvapp=Cerner
ucm=Cerner
AccessHIM=Cerner
RevenueCycle=Cerner
pmoffice=Cerner
mmdbtool=Cerner
mmrequisition=Cerner
mmrol=Cerner
mmreqtemplate=Cerner
mmreqrouting=Cerner
purchaseorder=Cerner
receiving=Cerner
invoicematching=Cerner
mmdistmanager=Cerner
mmphysicalcount=Cerner
mmadjustment=Cerner
itemlocbuild=Cerner
mmuploadmanager=Cerner
mmreqtemplate=Cerner
mmreportlauncher=Cerner
transaudit=Cerner
mmpointofuse=Cerner
mmpricingtool=Cerner
mmiteminquire=Cerner
itemclassbuild=Cerner
transacctmaintenance=Cerner
mmapproval=Cerner
mmpsrviewer=Cerner
manufmaintenance=Cerner
mmprofilebuild=Cerner
vendormaintenance=Cerner
financialacctbuild=Cerner
mmbarcodevalidator=Cerner
mmdbapproval=Cerner
mmdbbuyerrouting=Cerner
mmdbcontracttool=Cerner
mmdblog=Cerner
mmdbparlevel=Cerner
mmdbprsnlcatalog=Cerner
lot number maintenance=Cerner
cschargeviewer=Cerner
csbatchchargeentry=Cerner
pvapp=Cerner
FirstNet=Cerner
himletters=Cerner
himpatient deficiency analysis=Cerner
himphysician deficiency analysis=Cerner
phaBatchDispense=Cerner
phaBatchReport=Cerner
phaChargeCredit=Cerner
phaDBFreq=Cerner
phaMedMgr=Cerner
phaWorkstation=Cerner
phaDBProductMgr=Cerner
phaDBTools=Cerner
phaWorkflowMonitor=Cerner
pvinbox=Cerner
schreportexe=Cerner
schapptbook=Cerner
himchartcoding=Cerner
himchartabstracting=Cerner
himtaskqueue=Cerner
powerchart=msedge

;The following section defines the mapping between domain names and script sets.
;A script set includes JSB/JSS, JBS, JKM and JCF.
[Domains]
;This is a list of domains along with a script set to be loaded if the domain matches.
;This list is processed in order so the first entry in  the list that matches is the one that will be selected.
;If a line begins with with regex: then everything after the : up to the last = is interpreted as a regular expression that is tested against the current URL.
;if the regex matches, then the script set after the last = is loaded.
;To keep JAWS from loading any specific script set, just leave the entry after the = blank, this will cause JAWS to load the default script set for the current browser.
;
dev.azure.com=AzureDevOps
;Uncomment the following entry and ensure it points to your specific SharePoint portal if you wish to use the SharePoint test script:
;fsservices-my.sharepoint.com=SharePointWeb
;Google documents, spreadsheets, slides, etc.:
;published Docs
regex:https:\/\/docs.google.com\/document\/.*\/pub.*=
;published Sheets
regex:https:\/\/docs.google.com\/spreadsheets\/.*\/pubhtml=
;Published slides
regex:https:\/\/docs.google.com\/presentation\/.*\/pub.*=
regex:https:\/\/docs.google.com\/.*presentation\/.*\/htmlpresent=
;Published Forms
regex:https:\/\/docs.google.com\/forms\/.*\/viewform=
regex:https:\/\/docs.google.com\/forms\/.*\/formResponse=
docs.google.com=Google Docs
drive.google.com=Google Docs
mail.google.com=Gmail
regex:https?:\/\/outlook\.office\.com.*=Outlook Modern
regex:https?:\/\/outlook-sdf\.office\.com.*=Outlook Modern
regex:https?:\/\/outlook\.live\.com.*=Outlook Modern
regex:https?:\/\/outlook\.office365\.com.*=Outlook Modern
teams.microsoft.com=Teams
teams.live.com=Teams
regex:(https?:\/\/www\.audible\.)(.{2,})=www.audible.com
;CAI testing:
regex:https:\/\/.*tds(-uat)?\.cambiumast\.com\/student.*=CAI Testing
regex:https:\/\/.*\.cambiumtds(uat)?\.com\/student.*=CAI Testing
www.youtube.com=YouTube
regex:https:\/\/.*\.wikipedia\.org.*=wikipedia
regex:http(s)?:\/\/fscompanion.*\.freedomscientific\..*=FSCompanion
regex:https:\/\/.*crowdin\.com.*=Crowdin
