; JAWS 15.0
; Script message file for VMWare
Const
Id_SettingsTitle = "Virtual Machine Settings"
messages
@wmwareHotKeyHelp1
The following hot keys may be useful:
Description		hot key
Move focus to the search box, %KeyFor(MoveToFind).
Move focus to the tree view of virtual machines,  %KeyFor(MoveToTree).
Go to the selected running virtual machine (GrabInput), %KeyFor(GrabInput).

Press ESCAPE to close this message.
@@


EndMessages
