const
;const values
iWizard = 1,

;the following is a string constant, but is actually a list of control iD's for the ZipProperties dialog
strZipPropertiesControlsList = "5101\007 5107\007 5108\007 5110\007 5111\007 5112",

;control iD's
iDTipOfTheDayCombo = 9007,
iDStatic = 65535,
iDListViewDialogText = 8700,
iDListView = 8110,
iDSelectDifferentFolder = 8132,
iDEmptyButton = 2906,
iDIAgreeButton = 2901,
iDQuitButton = 2902,
iDEvalLicense = 2924,
iDThankYou = 2909,
iDEvalPeriod = 2923