; XML DOM NodeType Constant 

const
	XML_ELEMENT_NODE = 1,
	XML_ATTRIBUTE_NODE = 2,
	XML_TEXT_NODE = 3,
	XML_CDATA_SECTION_NODE = 4,
	XML_ENTITY_REFERENCE_NODE = 5,
	XML_ENTITY_NODE = 6,
	XML_PROCESSING_INSTRUCTION_NODE = 7,
	XML_COMMENT_NODE = 8,
	XML_DOCUMENT_NODE = 9,
	XML_DOCUMENT_TYPE_NODE = 10,
	XML_DOCUMENT_FRAGMENT_NODE = 11,
	XML_NOTATION_NODE= 12
